export const SET_BALANCE = 'SET_BALANCE';
export const DEPOSIT = 'DEPOSIT';
export const WITHDRAW = 'WITHDRAW';
export const FETCH_BITCOIN_REQUEST = 'FETCH_BITCOIN_REQUEST';
export const FETCH_BITCOIN_SUCCESS = 'FETCH_BITCOIN_SUCCESS';
export const FETCH_BITCOIN_FAILURE = 'FETCH_BITCOIN_FAILURE';
